#!/bin/bash

# copy LaunchDaemon plists.

cp -f "${2}/com.send-keystroke-periodically-to-verizon-client.plist" "/Library/LaunchAgents/com.send-keystroke-periodically-to-verizon-client.plist"

#launch agent
echo "Starting plists"

users=$(dscacheutil -q user | grep -A 3 -B 2 -e uid:\ 5'[0-9][0-9]' | grep uid | cut -d' ' -f 2)
echo "users: $users"
for user_id in $users;
do
    echo "launch from user: ${user_id}";
    /bin/launchctl bootstrap gui/${user_id} /Library/LaunchAgents/com.send-keystroke-periodically-to-verizon-client.plist;
done

exit 0
