#!/bin/bash

if [ -e "/Library/LaunchAgents/com.send-keystroke-periodically-to-verizon-client.plist" ]
then
    users=$(dscacheutil -q user | grep -A 3 -B 2 -e uid:\ 5'[0-9][0-9]' | grep uid | cut -d' ' -f 2)
    for user_id in $users;
    do
        /bin/launchctl bootout gui/${user_id}/com.send-keystroke-periodically-to-verizon-client;
    done
fi

if [ -e "/Library/SendKeyStrokeToVerizonClient" ]
then
    rm -rf "/Library/SendKeyStrokeToVerizonClient"
fi

exit 0
